#!/usr/bin/env python

import csv
import sys
import yaml

csv_data=[]
#group_data=[]

# find group to me made
#with open(sys.argv[1]) as csvfile:
#	reader=csv.DictReader(csvfile)
#	for row in reader:
#		if row['hostname'].find("gw") != -1:
#			print ("[gateway]")
#			csv_data.append("[gateway]")
#		if row['hostname'].find("fnkm") != -1:
#			print ("[fnkm]")
#			csv_data.append("[fnkm]")
#		csv_data.append(row)

# find group to me made
#with open(sys.argv[1]) as csvfile:
#print (line['inventory'])


# From the hosts file make the list of inventory groups.
inventory_categories= []
inventory_hosts=[]
inventory_data=dict()
with open(sys.argv[2]) as Rngroups:
  group_reader=csv.DictReader(Rngroups)
  for line in group_reader:
    with open('hosts.csv','r') as csvfile:
      reader=csv.DictReader(csvfile)
      for row in reader:
        group_data=row['hostname'].split('-')
        if group_data[-3].strip() == line['fun'].strip():
          inventory_categories.append(line['inventory'])
          inventory_hosts.append(row['hostname'])
          #inventory_data.append(row[?])


#print(inventory_categories)
inventory_categories.sort()
#print(inventory_categories)
b=set(inventory_categories)
print b
c=list(sorted(set(b)))

#print(inventory_hosts)
inventory_hosts.sort()
#print(inventory_hosts)
d=set(inventory_hosts)
#print d
e=list(sorted(set(d)))
#print e
#print (inventory_data)
#print (inventory_data['hostname'])
#print (inventory_data['ipaddress'])
#print c[0]
#print "server" " \n" .join(filter(lambda x: 'gw' in x, e))


## Create the inventory file


with open(sys.argv[2]) as Rngroups:
  group_reader=csv.DictReader(Rngroups)
  for line in group_reader:
    print (line['inventory'])
    function=line['fun'].strip()
    print "\n" .join(filter(lambda x: function in x, e))

#for line in f:
#    listedline = line.strip().split('=') # split around the = sign
#    if len(listedline) > 1: # we have the = sign in there
#        newDict[listedline[0]] = listedline[1]
f = open('Rn_groups.txt', 'r')
newDict = {}
for line in f:
    listedline = line.strip().split(',') # split around the = sign
    if len(listedline) > 1: # we have the = sign in there
        newDict[listedline[0]] = listedline[1]

#print (newDict)




for x in range(len(e)):
  with open('hosts.csv', "r") as csvfile2:
    f=csv.DictReader(csvfile2)
    dict = {}
    counter=1
    purpose_previous=''
    for line in f:
      if line['hostname']==e[x].strip():
        print("SERVER"+"{}" .format(x)+"_NAME="+ e[x].strip())
        print("SERVER"+"{}" .format(x)+"_IPV4ADDR="+ line['ipaddress'].strip())
        purpose=line['hostname'].split('-')
        #print(purpose[-3].strip())
        #print (purpose[-3])
        print("SERVER"+"{}" .format(x)+"_PURPOSE="+ newDict[purpose[-3]] )
        #purpose_previous=purpose[-3];
        #print("SERVER"+"{}" .format(x)+"_INSTANCE="+ counter)
        if counter == 1:
          if purpose_previous=='':
            purpose_previous=purpose[-3]
            print(purpose_previous)
            print (counter)
            counter=counter+1
        else:
          if purpose_previous==purpose[-3]:
            counter=counter + 1
            purpose_previous=purpose[-3];
            print (counter)
          else:
            counter=1
        #if line['hostname'][-3].strip() == b.['fun'].strip(): 
        #  print("SERVER"+"{}" .format(x)+"_PURPOSE="+ e[x].strip() )
        #print("SERVER"+"{}" .format(x)+"_INSTANCE="+ e[x].strip())

